//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEğtimKampı301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustumerId { get; set; }
        public string CustumerName { get; set; }
        public string CustumerSurname { get; set; }
        public Nullable<decimal> CustumerBalance { get; set; }
    }
}
